# These are supported funding model platforms

github: barryw
ko_fi: barryw
# buy_me_a_coffee: # uncomment and add username when set up
# custom: ["https://your-link.com"] # add any custom sponsorship URLs
