# Pull Request Pipeline - Build and test only
when:
  - event: pull_request

skip_clone: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone --depth=1 ${CI_REPO_CLONE_URL} .
      - git checkout ${CI_COMMIT_SHA}

  - name: restore
    image: mcr.microsoft.com/dotnet/sdk:10.0-preview
    commands:
      - dotnet restore
    depends_on: [clone]

  - name: build
    image: mcr.microsoft.com/dotnet/sdk:10.0-preview
    commands:
      - dotnet build --no-restore -c Release
    depends_on: [restore]

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:10.0-preview
    commands:
      - dotnet test --no-build -c Release --logger "console;verbosity=detailed"
    depends_on: [build]
