# Pull Request Pipeline - Build and test only
when:
  - event: pull_request

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      lfs: false

steps:
  - name: restore
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet restore

  - name: build
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet build --no-restore -c Release
    depends_on: [restore]

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet test --no-build -c Release --logger "console;verbosity=detailed"
    depends_on: [build]
