# Pull Request Pipeline - Build and test only
when:
  - event: pull_request

labels:
  platform: linux/amd64

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      lfs: false

steps:
  - name: build-and-test
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet restore
      - dotnet build -c Release
      - dotnet test -c Release --logger "console;verbosity=detailed"
